### ISSUE TITLE
No such command "rgbify".

### ISSUE THREAD

**Issue by jingsam** [mapbox/rio-rgbify#10]
I install rasterio and rio-rgbify:
```
brew install gdal
sudo -H pip install rasterio
sudo -H pip install rio-rgbify
```

When I use:
```
rio rgbify aa.tiff aa.mbtiles
```

I get this error:
```
Usage: rio [OPTIONS] COMMAND [ARGS]...

Error: No such command "rgbify".
```

Anything am I missing?

**Comment by dnomadb** [comment]
@jingsam it appears that the version on PyPi does not include this PR, which fixes the rasterio API change: https://github.com/mapbox/rio-rgbify/pull/7. As such, the extension cannot be loaded -- my apologies! I'll get a version bump + publish going tomorrow, but feel free to clone + install via github as noted [here](https://github.com/mapbox/rio-rgbify#development); this should work.

**Comment by jingsam** [comment]
Many thanks. Have a good day!

**Comment by dnomadb** [comment]
@jingsam --> https://pypi.python.org/pypi/rio-rgbify/0.3.1

If it works, feel free to close this issue.

**Comment by jingsam** [comment]
Wired, I uninstall rgbify and reinstall rgbify 0.3.1, still errors. Should I also reinstall rasterio? Note that I am using macOS 10.13.2. and pip install with `sudo -H`

**Comment by dnomadb** [comment]
@jingsam hmm. I'd recommend (if you are not):
- Downloading and using python from python.org (probably 3.x), it includes `pip` + `virtualenv`. If not, use a homebrew python.
- Using a virtualenv to both (a) keep your python environments more manageable, and (b) not require `sudo` upon pip installing (which [can be a security risk](https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip))
- Once you create a virtualenv, you can:
    - `pip install numpy` (required for rasterio)
    - `pip install rasterio --pre` (uses compiled wheels for gdal binaries)
    - `pip install rio-rgbify`
    - or, `cd` into a cloned `rio-rgbify`, `pip install -e '.[test]'

I know this sounds like a lot, but I have found that `virtualenvs` end up saving me a lot of work installing + uninstalling python packages in the future.

All this said, you should def try reinstalling rasterio, and make sure you have all these requirements installed:  https://github.com/mapbox/rio-rgbify/blob/master/requirements.txt

What happens when you `pip freeze | grep rasterio` ?

**Comment by jingsam** [comment]
I successfuly installed rio-rgbify with virtualenv. Many thanks. But I would like to test installing without virtualenv, figure out why this happens.

**Comment by jacquestardie** [comment]
Glad you got it working @jingsam! Given that, I'm gonna close here.
